[package]

name = "rusty-tags"
version = "2.2.0"
authors = ["Daniel Trstenjak <daniel.trstenjak@gmail.com>"]
license = "BSD-3-Clause"
description = "Create ctags/etags for a cargo project and all of its dependencies"
repository = "https://github.com/dan-t/rusty-tags"
readme = "README.md"

[dependencies]
toml = "~0.2.0"
clap = "~2.10.0"
lazy_static = "~0.2.1"
rustc-serialize = "~0.3.19"
tempfile = "~2.1.5"
